<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Pasien_rajal extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        is_login();
        $this->load->model('Pasien_rajal_model');
        //$this->load->library('form_validation');
    }

    public function index()
    {
        if (!empty($_GET['tgl'])) {
            $tgl = $_GET['tgl'];
        } else {
            $tgl = date('Y-m-d');
        }
        $url = "http://192.168.1.121/simrs/service_dirut.php?param=list_pasien_rajal&tgl=" . $tgl;
        $get_url = file_get_contents($url);
        $data_array = json_decode($get_url);

        $data = array(
            'datalist' => $data_array
        );
        $this->template->load('template', 'pasien_rajal/rajal_list', $data);
    }
    public function read($iddaftar)
    {
        $url = "http://192.168.1.121/simrs/service_dirut.php?param=list_pasien_rajal_detail&id=" . $iddaftar;
        $get_url = file_get_contents($url);
        $data_array = json_decode($get_url);

        $data = array(
            'datalist' => $data_array,
            'menuemr' => $this->Pasien_rajal_model->get_menuemr(),
        );
        $this->template->load('template', 'pasien_rajal/rajal_read', $data);
    }
}

/* End of file Test.php */
/* Location: ./application/controllers/Test.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2020-05-07 18:40:47 */
/* http://harviacode.com */
