<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Pasien_rajal_model extends CI_Model
{

    public $table = 'test';
    public $id = 'id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_menuemr()
    {
        $this->db->select('*');
        $this->db->from('t_menu_emr');
        $this->db->where('aktif', 'Y');
        $this->db->group_by('tabel');
        return $this->db->get()->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
}

/* End of file Test_model.php */
/* Location: ./application/models/Test_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2020-05-07 20:04:09 */
/* http://harviacode.com */
