<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class T_assesment_awal_rjjiwa_model extends CI_Model
{

    public $table = 't_assesment_awal_rjjiwa';
    public $id = 'ID_ASS';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    function get_datalist($nomr,$idxdaftar)
    {
        $this->db->where('idxdaftar', $idxdaftar);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('ID_ASS', $q);
	$this->db->or_like('IDXDAFTAR', $q);
	$this->db->or_like('NOMR', $q);
	$this->db->or_like('ALERGI', $q);
	$this->db->or_like('JAMMULAI', $q);
	$this->db->or_like('ANAMNESE', $q);
	$this->db->or_like('KELUHAN_UTAMA', $q);
	$this->db->or_like('RIWAYAT_PENYAKIT_SEKARANG', $q);
	$this->db->or_like('RIWAYAT_PENYAKIT_DULU_SEKARANG', $q);
	$this->db->or_like('RIWAYAT_KELUARGA', $q);
	$this->db->or_like('PEMERIKSAAN_STATUS_MENTAL', $q);
	$this->db->or_like('PEMERIKSAAN_PENUNJANG', $q);
	$this->db->or_like('DIAGNOSA_KERJA', $q);
	$this->db->or_like('TERAPI', $q);
	$this->db->or_like('KONTROL_ULANG_TGL', $q);
	$this->db->or_like('RAWAT_INAP', $q);
	$this->db->or_like('RUJUK_LUAR', $q);
	$this->db->or_like('RUJUK_LAINNYA', $q);
	$this->db->or_like('TTD_PASIEN', $q);
	$this->db->or_like('TTD_DOKTER', $q);
	$this->db->or_like('ID_DOKTER', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('ID_ASS', $q);
	$this->db->or_like('IDXDAFTAR', $q);
	$this->db->or_like('NOMR', $q);
	$this->db->or_like('ALERGI', $q);
	$this->db->or_like('JAMMULAI', $q);
	$this->db->or_like('ANAMNESE', $q);
	$this->db->or_like('KELUHAN_UTAMA', $q);
	$this->db->or_like('RIWAYAT_PENYAKIT_SEKARANG', $q);
	$this->db->or_like('RIWAYAT_PENYAKIT_DULU_SEKARANG', $q);
	$this->db->or_like('RIWAYAT_KELUARGA', $q);
	$this->db->or_like('PEMERIKSAAN_STATUS_MENTAL', $q);
	$this->db->or_like('PEMERIKSAAN_PENUNJANG', $q);
	$this->db->or_like('DIAGNOSA_KERJA', $q);
	$this->db->or_like('TERAPI', $q);
	$this->db->or_like('KONTROL_ULANG_TGL', $q);
	$this->db->or_like('RAWAT_INAP', $q);
	$this->db->or_like('RUJUK_LUAR', $q);
	$this->db->or_like('RUJUK_LAINNYA', $q);
	$this->db->or_like('TTD_PASIEN', $q);
	$this->db->or_like('TTD_DOKTER', $q);
	$this->db->or_like('ID_DOKTER', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file T_assesment_awal_rjjiwa_model.php */
/* Location: ./application/models/T_assesment_awal_rjjiwa_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2020-05-30 05:46:09 */
/* http://harviacode.com */